apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart-test.fullname" . }}
  labels:
    {{- include "helm-chart-test.labels" . | nindent 4 }}
data:
  API_PORT: {{ .Values.service.port }}
